name:                servant-tools
version:             0.1.0.0
github:              "jabaraster/servant-tools"
license:             BSD-3-Clause
author:              "jabaraster"
maintainer:          "jabaraster"
copyright:           "2025 jabaraster"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jabaraster/servant-tools#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- bytestring
- file-embed
- template-haskell
- filepath
- http-media
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  servant-tools-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-tools
